EventAssessment/Models/Assessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using NPoco;

namespace EventAssessment.Models
{
    [TableName("tblAssessment")]
    [PrimaryKey("id")]
    public class Assessment
    {
        public int id { get; set; }
        public int event_id { get; set; }

        [Required]
        [Display(Name = "Are you more likely to use the library now that you have attend this event or program?")]
        public bool? more_likely { get; set; }

        [Required]
        [Display(Name = "Did this event or program increase your knowledge about the services, collections, and/or resources the library has to offer?")]
        public bool? increase_knowledge { get; set; }

        [Required]
        [Display(Name = "Would you recommend this event or program to others?")]
        public bool? recommend { get; set; }

        [DataType(DataType.MultilineText)]
        public string library_use { get; set; }

        [Ignore]
        public string library_use_other { get; set; }

        [Ignore]
        public HearAboutEventList HearAboutEvents { get; set; }

        [DataType(DataType.MultilineText)]
        public string how_hear { get; set; }

        [Ignore]
        public string how_hear_more { get; set; }

        [Ignore]
        public WhyAttendList WhyAttends { get; set; }

        [DataType(DataType.MultilineText)]
        public string why_attend { get; set; }

        [Ignore]
        public string why_attend_more { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "What was the most important or helpful part of this event for you?")]
        public string how_helpful { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "How could this event/program be improved?")]
        public string how_improved { get; set; }

        public bool? learn_more { get; set; }

        [DataType(DataType.MultilineText)]
        public string contact { get; set; }

        public string use_responses { get; set; }

        public DateTime submitted { get; set; }
    }

    public class AssessmentEvent : Assessment
    {
        public string title { get; set; }
        public StrategicPriority? priority_id { get; set; }
        public bool? assessed { get; set; }
    }

    public class EventWithAssessments
    {
        public List<Assessment> AssessmentList { get; set; }
        public Event Event { get; set; }
        

    }
}

EventAssessment/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using EventAssessment.Models;
using EventAssessment.Services;

namespace EventAssessment.Controllers
{
    public class AssessmentController : BaseController
    {
        [CustomAuthorize("Administrators")]
        public ActionResult Index()
        {
            return View(EventRepo.GetUnAssessed());
        }

        [CustomAuthorize("Administrators")]
        public ActionResult View(int id)
        {
            var vm = EventRepo.GetAssessmentView(id);
            return View(vm);
        }

        [CustomAuthorize("Administrators")]
        public ActionResult List(int id)
        {
            var vm = EventRepo.GetAssessmentList(id);
            return View(vm);
        }

        [AllowAnonymous]
        public ActionResult Feedback(int id)
        {
            var vm = EventRepo.GetAssessmentEvent(id);

            vm.how_hear = vm.how_hear ?? string.Empty;
            vm.HearAboutEvents = new HearAboutEventList();
            vm.HearAboutEvents.Items = new List<HearAboutEvent>
            {
                new HearAboutEvent {Text = "Email", Value = "1", IsChecked = vm.how_hear.Contains("1")},
                new HearAboutEvent {Text = "Social media", Value = "2", IsChecked = vm.how_hear.Contains("2")},
                new HearAboutEvent {Text = "Website", Value = "3", IsChecked = vm.how_hear.Contains("3")},
                new HearAboutEvent {Text = "Class/Instructor", Value = "4", IsChecked = vm.how_hear.Contains("4")},
                new HearAboutEvent {Text = "Friend", Value = "5", IsChecked = vm.how_hear.Contains("5")},
                new HearAboutEvent {Text = "Other (specify below)", Value = "6", IsChecked = vm.how_hear.Contains("6")}
            };

            vm.why_attend = vm.why_attend ?? string.Empty;
            vm.WhyAttends = new WhyAttendList();
            vm.WhyAttends.Items = new List<WhyAttend>
            {
                new WhyAttend {Text = "Class requirement or incentive", Value = "1", IsChecked = vm.why_attend.Contains("1")},
                new WhyAttend {Text = "Interest in topic    ", Value = "2", IsChecked = vm.why_attend.Contains("2")},
                new WhyAttend {Text = "Related to area of study", Value = "3", IsChecked = vm.why_attend.Contains("3")},
                new WhyAttend {Text = "Passport event", Value = "4", IsChecked = vm.why_attend.Contains("4")},
                new WhyAttend {Text = "Other (specify below)", Value = "5", IsChecked = vm.why_attend.Contains("5")}
            };
            return View(vm);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Feedback(AssessmentEvent ae)
        {
            if (ae.library_use == "Other")
            {
                ae.library_use = ae.library_use += ": " + ae.library_use_other;
            }
            ae.submitted = DateTime.Now;

            ae.how_hear = ae.how_hear_more + ae.how_hear;
            ae.why_attend = ae.why_attend_more + ae.why_attend;
            EventRepo.InsertFeedback(ae);
            return RedirectToAction("Success");
        }

        [AllowAnonymous]
        public ActionResult Success()
        {
            return View();
        }
    }
}

EventAssessment/Views/Assessment/Feedback.cshtml
@using EventAssessment.Models
@model EventAssessment.Models.AssessmentEvent
@{
    ViewBag.Title = "Event Feedback";
}

<h2>Feedback for @Model.title</h2>
<hr/>
<div class="alert alert-danger col-md-6" role="alert">
    Fields marked with and asterisk (*) are mandatory.
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.event_id)
    <div class="form-group">
        @Html.LabelFor(m => m.more_likely) <span class="mr-2">*</span><br/>
        @Html.RadioButtonFor(model => model.more_likely, "true")<span class="ml-1 mr-3">Yes</span>
        @Html.RadioButtonFor(model => model.more_likely, "false")<span class="ml-1 mr-3">No</span>
        @Html.ValidationMessageFor(m => m.more_likely, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.increase_knowledge) <span class="mr-2">*</span><br />
        @Html.RadioButtonFor(model => model.increase_knowledge, "true")<span class="ml-1 mr-3">Yes</span>
        @Html.RadioButtonFor(model => model.increase_knowledge, "false")<span class="ml-1 mr-3">No</span>
        @Html.ValidationMessageFor(m => m.increase_knowledge, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.recommend) <span class="mr-2">*</span><br />
        @Html.RadioButtonFor(model => model.recommend, "true")<span class="ml-1 mr-3">Yes</span>
        @Html.RadioButtonFor(model => model.recommend, "false")<span class="ml-1 mr-3">No</span>
        @Html.ValidationMessageFor(m => m.recommend, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>How do you use the library? (choose one) *</label>
        <div class="list-group col-md-6 mb-3">
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "ECUUndergraduate", new { Checked = "checked" })<span class="ml-1 mr-3">ECU Undergraduate Student</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "ECUGraduate")<span class="ml-1 mr-3">ECU Graduate Student</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "ECUFacultyStaff")<span class="ml-1 mr-3">ECU Faculty/Staff</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "VisitingFacultyStaff")<span class="ml-1 mr-3">Visiting Faculty/Staff</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "VisitingStudent")<span class="ml-1 mr-3">Visiting Student</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "CommunityMember")<span class="ml-1 mr-3">Community Member</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "AreaEducator")<span class="ml-1 mr-3">Area Educator</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.library_use, "Other")<span class="ml-1 mr-3">Other</span><br/>
                @Html.EditorFor(m => m.library_use_other, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.library_use_other, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>How did you hear about this event? (choose as many as apply)</label><br />
        @for (var i = 0; i < Model.HearAboutEvents.Items.Count; i++)
        {
            @Html.CheckBoxFor(m => Model.HearAboutEvents.Items[i].IsChecked)
            <span class="ml-1 mr-3">@Model.HearAboutEvents.Items[i].Text</span>
            @Html.HiddenFor(m => Model.HearAboutEvents.Items[i].Value)
            @Html.HiddenFor(m => Model.HearAboutEvents.Items[i].Text)<br />
        }
    </div>
    <div style="color:red">@Html.ValidationSummary(false)</div>
    <div class="form-group">
        @Html.EditorFor(m => m.how_hear_more, new { htmlAttributes = new { @class = "form-control col-md-6" } })
    </div>
    <div class="form-group">
        <label>Why did you choose to attend this event or program? (choose as many as apply)</label><br />
        @for (var i = 0; i < Model.WhyAttends.Items.Count; i++)
        {
            @Html.CheckBoxFor(m => Model.WhyAttends.Items[i].IsChecked)
            <span class="ml-1 mr-3">@Model.WhyAttends.Items[i].Text</span>
            @Html.HiddenFor(m => Model.WhyAttends.Items[i].Value)
            @Html.HiddenFor(m => Model.WhyAttends.Items[i].Text)<br />
        }
    </div>
    <div style="color:red">@Html.ValidationSummary(false)</div>
    <div class="form-group">
        @Html.EditorFor(m => m.why_attend_more, new { htmlAttributes = new { @class = "form-control col-md-6" } })
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.how_helpful)
        @Html.EditorFor(m => m.how_helpful, new { htmlAttributes = new { @class = "form-control col-md-6" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.how_improved)
        @Html.EditorFor(m => m.how_improved, new { htmlAttributes = new { @class = "form-control col-md-6" } })
    </div>
    <div class="form-group">
        @switch (Model.priority_id)
        {
            case StrategicPriority.MaximizeStudentSuccess:
                <label>The library is here to help! Would you like to learn more about how the library can support you with your classes?</label><br/>
            break;
            case StrategicPriority.ImpactResearch:
                <label>Would you like to learn more about how the library can support your research?</label><br />
                break;
            case StrategicPriority.ServeThePublic:
                <label>Would you like more information regarding library resources that support regional history, cultural experiences, and lifelong learning?</label><br />
                break;
            case StrategicPriority.Stewardship:
                <label>Would you like more information about supporting library programming?</label><br />
                break;
        }
        @Html.RadioButtonFor(model => model.learn_more, "true")<span class="ml-1 mr-3">Yes</span>
        @Html.RadioButtonFor(model => model.learn_more, "false", new{@checked="true"})<span class="ml-1 mr-3">No</span>
    </div>
    
    <div class="form-group">
        <label>IF yes,- Please provide us with your prefered method contact?</label><br/>
        @Html.EditorFor(m => m.contact, new { htmlAttributes = new { @class = "form-control col-md-6" } })
    </div>

    <div class="form-group">
        <label>Will you allow us to use portions of your responses in future promotional material?</label>
        <div class="list-group col-md-6 mb-3">
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.use_responses, "Yes", new { Checked = "checked" })<span class="ml-1 mr-3">Yes</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.use_responses, "Anonymously")<span class="ml-1 mr-3">Yes, but anonymously</span>
            </div>
            <div class="list-group-item">
                @Html.RadioButtonFor(model => model.use_responses, "No")<span class="ml-1 mr-3">No</span>
            </div>
        </div>
    </div>

    <input type="submit" value="Submit" class="btn btn-primary" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EventAssessment/Views/Assessment/Index.cshtml
@model List<EventAssessment.Models.EvtItemViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Assessment</h2>
<hr />
@if (Model.Count > 0)
{
    foreach (var evt in Model)
    {
        <div class="card">
            <div class="card-header">
                <h6 class="card-subtitle text-muted">@evt.name</h6>
            </div>
            <div class="card-body">
                <h4 class="card-text"><a href="@Url.Action("Feedback", "Assessment", new { id = evt.id} )">@evt.title</a></h4>
                @if (@evt.start_at.Date == @evt.end_at.Date)
                {
                    <p class="card-text">@evt.start_at.ToString("D"), @evt.start_at.ToShortTimeString() - @evt.end_at.ToShortTimeString() - <a href="@Url.Action("Review", "Manage", new { id = evt.id} )">Event Details</a></p>
                }
                else
                {
                    <p class="card-text">@evt.start_at.ToString("D"), @evt.start_at.ToShortTimeString() - @evt.end_at.ToString("D"), @evt.end_at.ToShortTimeString() - <a href="@Url.Action("Review", "Manage", new { id = evt.id} )">Event Details</a></p>
                }
                
                @if (evt.assessment_count > 0)
                {
                    <a href="@Url.Action("List", "Assessment", new { evt.id })" class="btn btn-primary mb-3">
                        Event Feedback <span class="badge badge-light">@evt.assessment_count</span>
                    </a>
                }
                else
                {
                    <div class="mb-4">No feedback received</div>
                }


                @using (Html.BeginForm("Assess", "Manage", FormMethod.Post))
                {
                    <input type="hidden" id="id" name="id" value="@evt.id" />
                    <input type="submit" class="btn btn-danger" value="Close Assessment" onclick="return confirm('Are you sure you want to close assessment for this event?');"/>
                    
                }

            </div>
        </div>
        <br />
    }
}

EventAssessment/Views/Assessment/List.cshtml
@using System.Text.RegularExpressions
@using EventAssessment.Models
@model EventWithAssessments
@{
    ViewBag.Title = "List";
}

<h2>Feedback for @Model.Event.title</h2>
<hr/>



@foreach (var item in Model.AssessmentList)
{
    <div class="card bg-light mb-4">
        <div class="card-header">
            Received @item.submitted.ToString("f")
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-6">@Html.LabelFor(m => item.more_likely)</dt>
                <dd class="col-sm-6">@(item.more_likely.Value ? "Yes" : "No")</dd>
                <dt class="col-sm-6">@Html.LabelFor(m => item.increase_knowledge)</dt>
                <dd class="col-sm-6">@(item.increase_knowledge.Value ? "Yes" : "No")</dd>
                <dt class="col-sm-6">@Html.LabelFor(m => item.recommend)</dt>
                <dd class="col-sm-6">@(item.recommend.Value ? "Yes" : "No")</dd>
                <dt class="col-sm-6"><label>How do you use the library?</label></dt>
                <dd class="col-sm-6">@item.library_use</dd>
                <dt class="col-sm-6"><label>How did you hear about this event?</label></dt>
                <dd class="col-sm-6">
                    @{
                        var digitsOnly = new Regex(@"[^\d]");
                        var stripped = digitsOnly.Replace(item.how_hear, "");
                    }
                    @foreach (var c in stripped.Trim().ToCharArray())
                    {
                        switch (c)
                        {
                            case '1':
                                <text>Email; </text>
                                break;
                            case '2':
                                <text>Social media; </text>
                                break;
                            case '3':
                                <text>Website; </text>
                                break;
                            case '4':
                                <text>Class/Instructor; </text>
                                break;
                            case '5':
                                <text>Friend; </text>
                                break;
                            case '6':
                                <text>Other: @item.how_hear.Replace(stripped, "") </text>
                                break;
                        }
                    }
                </dd>
                <dt class="col-sm-6"><label>Why did you choose to attend this event or program?</label></dt>
                <dd class="col-sm-6">
                    @{
                        var stripped2 = digitsOnly.Replace(item.why_attend, "");
                    }
                    @foreach (var c in stripped2.Trim().ToCharArray())
                    {
                        switch (c)
                        {
                            case '1':
                                <text>Class requirement or incentive; </text>
                                break;
                            case '2':
                                <text>Interest in topic; </text>
                                break;
                            case '3':
                                <text>Related to area of study; </text>
                                break;
                            case '4':
                                <text>Passport event; </text>
                                break;
                            case '5':
                                <text>Other: @item.why_attend.Replace(stripped2, "") </text>
                                break;
                        }
                    }
                </dd>
                <dt class="col-sm-6">@Html.LabelFor(m => item.how_helpful)</dt>
                <dd class="col-sm-6">@item.how_helpful</dd>
                <dt class="col-sm-6">@Html.LabelFor(m => item.how_improved)</dt>
                <dd class="col-sm-6">@item.how_improved</dd>
                @switch (Model.Event.priority_id)
                {
                    case StrategicPriority.MaximizeStudentSuccess:
                        <dt class="col-sm-6">The library is here to help! Would you like to learn more about how the library can support you with your classes?</dt>
                        break;
                    case StrategicPriority.ImpactResearch:
                        <dt class="col-sm-6">Would you like to learn more about how the library can support your research?</dt>
                        break;
                    case StrategicPriority.ServeThePublic:
                        <dt class="col-sm-6">Would you like more information regarding library resources that support regional history, cultural experiences, and lifelong learning?</dt>
                        break;
                    case StrategicPriority.Stewardship:
                        <dt class="col-sm-6">Would you like more information about supporting library programming?</dt>
                        break;
                }
                <dd class="col-sm-6">@(item.learn_more.Value ? "Yes" : "No")</dd>

                <dt class="col-md-6"><label>IF yes,- Please provide us with your prefered method contact?</label></dt>
                <dd class="col-sm-6">@item.contact</dd>
                <dt class="col-md-6"><label>Will you allow us to use portions of your responses in future promotional material? </label></dt>
                <dd class="col-sm-6">@item.use_responses</dd>
            </dl>
        </div>
    </div>
    

}

EventAssessment/Views/Assessment/Success.cshtml
@{
    ViewBag.Title = "Success";
}

<h2>Thanks for providing feedback!</h2>

EventAssessment/Views/Assessment/View.cshtml
@using System.Text.RegularExpressions
@using EventAssessment.Models
@model EventAssessment.Models.AssessmentEvent
@{
    ViewBag.Title = "View";
}

<h2>View Assessment for @Model.title</h2>
<label>Received @Model.submitted.ToString("f")</label>
<hr/>
<dl class="row">
    <dt class="col-sm-6">@Html.LabelFor(m => m.more_likely)</dt>
    <dd class="col-sm-6">@(Model.more_likely.Value ? "Yes" : "No")</dd>
    <dt class="col-sm-6">@Html.LabelFor(m => m.increase_knowledge)</dt>
    <dd class="col-sm-6">@(Model.increase_knowledge.Value ? "Yes" : "No")</dd>
    <dt class="col-sm-6">@Html.LabelFor(m => m.recommend)</dt>
    <dd class="col-sm-6">@(Model.recommend.Value ? "Yes" : "No")</dd>
    <dt class="col-sm-6"><label>How do you use the library?</label></dt>
    <dd class="col-sm-6">@Model.library_use</dd>
    <dt class="col-sm-6"><label>How did you hear about this event?</label></dt>
    <dd class="col-sm-6">
        @{
            var digitsOnly = new Regex(@"[^\d]");
            var stripped = digitsOnly.Replace(Model.how_hear, "");
        }
        @foreach (var c in stripped.Trim().ToCharArray())
        {
            switch (c)
            {
                case '1':
                    <text>Email; </text>
                    break;
                case '2':
                    <text>Social media; </text>
                    break;
                case '3':
                    <text>Website; </text>
                    break;
                case '4':
                    <text>Class/Instructor; </text>
                    break;
                case '5':
                    <text>Friend; </text>
                    break;
                case '6':
                    <text>Other: @Model.how_hear.Replace(stripped, "") </text>
                    break;
            }
        }
    </dd>
    <dt class="col-sm-6"><label>Why did you choose to attend this event or program?</label></dt>
    <dd class="col-sm-6">
        @{
            var stripped2 = digitsOnly.Replace(Model.why_attend, "");
        }
        @foreach (var c in stripped2.Trim().ToCharArray())
        {
            switch (c)
            {
                case '1':
                    <text>Class requirement or incentive; </text>
                    break;
                case '2':
                    <text>Interest in topic; </text>
                    break;
                case '3':
                    <text>Related to area of study; </text>
                    break;
                case '4':
                    <text>Passport event; </text>
                    break;
                case '5':
                    <text>Other: @Model.why_attend.Replace(stripped2, "") </text>
                    break;
            }
        }
    </dd>
    <dt class="col-sm-6">@Html.LabelFor(m => m.how_helpful)</dt>
    <dd class="col-sm-6">@Model.how_helpful</dd>
    <dt class="col-sm-6">@Html.LabelFor(m => m.how_improved)</dt>
    <dd class="col-sm-6">@Model.how_improved</dd>
    @switch (Model.priority_id)
    {
        case StrategicPriority.MaximizeStudentSuccess:
            <dt class="col-sm-6">The library is here to help! Would you like to learn more about how the library can support you with your classes?</dt>
            break;
        case StrategicPriority.ImpactResearch:
            <dt class="col-sm-6">Would you like to learn more about how the library can support your research?</dt>
            break;
        case StrategicPriority.ServeThePublic:
            <dt class="col-sm-6">Would you like more information regarding library resources that support regional history, cultural experiences, and lifelong learning?</dt>
            break;
        case StrategicPriority.Stewardship:
            <dt class="col-sm-6">Would you like more information about supporting library programming?</dt>
            break;
    }
    <dd class="col-sm-6">@(Model.learn_more.Value ? "Yes" : "No")</dd>
    
    <dt class="col-md-6"><label>IF yes,- Please provide us with your prefered method contact?</label></dt>
    <dd class="col-sm-6">@Model.contact</dd>
    <dt class="col-md-6"><label>Will you allow us to use portions of your responses in future promotional material? </label></dt>
    <dd class="col-sm-6">@Model.use_responses</dd>
</dl>